# Server configurations
server:
  port: :8080

application:
  name: gitworkflow-microservice
  doc: http://localhost:8080

github:
  url: https://github.com/arunprasath42/git-service

logging:
  level: DEBUG
